routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

Auth::routes();

/* Rutas del Administrador */
Route::group(['middleware' => 'admin'], function () {
    Route::resource('users', 'UserController');
    Route::get('users', 'UserController@index')->name('users');

    Route::get('listar_por_usuarios', 'ProcesosController@listar_por_usuarios')->name('listar_por_usuarios');
});

/* Rutas Generales */
Route::group(['middleware' => 'auth'], function () {
    /* Página principal */
    Route::get('/home', 'HomeController@index')->name('home');
    /* Rutas de procesos */
    Route::resource('procesos', 'ProcesosController');
    Route::get('procesos', 'ProcesosController@index')->name('procesos');
    /* Rutas de Perfil de usuario */
    Route::resource('user', 'UserController');
    Route::get('edit-user, {id}', 'UserController@editSessionUser')->name('edit-user');
    Route::put('update-user, {id}', 'UserController@updateSessionUser')->name('update-user');
    Route::get('change-user-password','UserController@changeUserPassword')->name('change-user-password');
    Route::post('saveNewPassword','UserController@saveNewPassword')->name('saveNewPassword');
});

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    // relacion entre el modelo user y el modelo role
    public function roles()
    {
        return $this
            ->belongsToMany('App\Role')
            ->withTimestamps();
    }

    // metodos de autorización según los roles de usuario
    public function authorizeRoles($roles)
    {
        if ($this->hasAnyRole($roles)) {
            return true;
        }
        abort(401, 'Esta acción no está autorizada.');
    }

    public function hasAnyRole($roles)
    {
        if (is_array($roles)) {
            foreach ($roles as $role) {
                if ($this->hasRole($role)) {
                    return true;
                }
            }
        } else {
            if ($this->hasRole($roles)) {
                return true;
            }
        }
        return false;
    }

    public function hasRole($role)
    {
        if ($this->roles()->where('nombre', $role)->first()) {
            return true;
        }
        return false;
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;
use Hash;
use App\User;
use App\Role;

class UserController extends Controller
{

  public function index()
    {
        // listar usuarios
        $users = User::orderBy('id','ASC')
                       ->where('id', '!=', $id = Auth::id())
                       ->get();
        // retornar a la vista
        return view('users.list-users', compact('users'));
    }

    public function edit($id)
    {
        // buscar datos de usuario por id
        $users = User::find($id);
        // retornar consulta a la vista de actualizar datos
        return \View::make('users.update-user', compact('users'));
    }
    public function update(Request $request, $id)
    {
        // actualziar datos
        $user = User::find($id);

        $user->name = $request->name;
        $user->email = $request->email;
        // mensajes de acción
        if ($user->save()) {
          return redirect('/users')->with('msj','Usuario actualizado correctamente.');
         }else{
          return redirect('/users')->with('msjerror','Ha sucedido un error al actualizar los datos de usuario.');
        }
    }

    // editar datos de usuario en sesión
    public function editSessionUser($id)
    {
        // Recibe el parametro id del registro a modificar
        $users = User::find($id);
        return \View::make('users.update-session-user', compact('users'));
    }

    public function updateSessionUser(Request $request, $id)
      {
          // actualizar perfil de usuario
          $user = User::find($id);

          $user->name = $request->name;
          $user->email = $request->email;

          if ($user->save()) {
            return redirect('/home')->with('msj','Sus datos de perfil de usuario han sido actualizados correctamente.');
           }else{
            return redirect('/home')->with('msjerror','Ha sucedido un error al actualizar los datos de su perfil de usuario.');
          }
      }

      // vista para cambiar contraseña
      public function changeUserPassword(){
          return \View::make('users.change-user-password');
      }

      // función para guardar el cambio de la contraseña
      public function saveNewPassword(Request $request){

          if (!(Hash::check($request->get('contraseña-actual'), Auth::user()->password))) {
              // contraseña actual no coincide
              return redirect()->back()->with("msjerror","Su contraseña actual no coincide con la ingresada recientemente, por favor revise e intente nuevamente.");
          }

          if(strcmp($request->get('contraseña-actual'), $request->get('nueva-contraseña')) == 0){
              // contraseña actual y contraseña nueva son iguales
              return redirect()->back()->with("msjerror","su nueva contraseña no puede ser igual a la actual, por favor ingrese una contraseña diferente.");
          }

          $validatedData = $request->validate([
              'contraseña-actual' => 'required',
              'nueva-contraseña' => 'required|string|min:6|confirmed',
          ]);

          //Change Password
          $user = Auth::user();
          $user->password = bcrypt($request->get('nueva-contraseña'));
          $user->save();

          return redirect('/home')->with("msj","Su contraseña de ingreso se actualizó correctamente en el sistema!");

      }

}

resources/views/users/change-user-password.blade.php
@extends('layouts.app')
@section('content')
<div class="container" style="text-align: center;">
  @if(session('msj'))
      <div class="alert alert-success alert-dismissible fade show" role="alert">
              {{session('msj')}}
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
          </button>
      </div>
  @endif
  @if(session('msjerror'))
      <div class="alert alert-danger alert-dismissible fade show" role="alert">
              {{session('msjerror')}}
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
          </button>
      </div>
  @endif
</div>
<div class="container">
  <h3 style="text-align: center; margin-top: 8px; margin-bottom: 1%;">Actualizar Contraseña de Usuario</h3>
    <div class="row" style="width: 100%;">
        <div class="col-md-8 col-md-offset-2" style="margin-left: 34%;">
            <div class="panel panel-default">

                <div class="panel-body">
                    <form method="POST" action="{{ route('saveNewPassword') }}" style="font-size: 16px; color: black;">
                        {{ csrf_field() }}

                        <div class="form-group{{ $errors->has('contraseña-actual') ? ' has-error' : '' }}">
                            <label style="margin-left: 13%;" for="new-password" class="col-md-4 control-label">Contraseña Actual</label>

                            <div class="col-md-6">
                                <input id="contraseña-actual" type="password" style="border-color: black;" class="form-control" name="contraseña-actual" required>

                                @if ($errors->has('contraseña-actual'))
                                    <span class="help-block" style="color: red;">
                                        <strong>{{ $errors->first('contraseña-actual') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('nueva-contraseña') ? ' has-error' : '' }}">
                            <label style="margin-left: 13%;" for="nueva-contraseña" class="col-md-4 control-label">Nueva Contraseña</label>

                            <div class="col-md-6">
                                <input id="nueva-contraseña" type="password" style="border-color: black;" class="form-control" name="nueva-contraseña" required>

                                @if ($errors->has('nueva-contraseña'))
                                    <span class="help-block" style="color: red;">
                                        <strong>{{ $errors->first('nueva-contraseña') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group">
                            <label style="margin-left: 9%;" for="nueva-contraseña-confirm">Confirmar Nueva Contraseña</label>

                            <div class="col-md-6">
                                <input id="nueva-contraseña-confirm" type="password" style="border-color: black; margin-bottom: 10%;" class="form-control" name="nueva-contraseña_confirmation" required>
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-6 col-md-offset-4">
                                <button type="submit" style="margin-left: 18%; padding: 6%; border-radius: 28px;" id="botones" class="btn btn-primary">Actualizar Contraseña
                                  <i style="margin-left: 5px; vertical-align: middle;" class="material-icons">update</i>
                                </button>
                                <a class="btn btn-outline-danger py-2 mt-2" id="boton_menu" href="{{ route('home') }}">
                                    Volver al Menú Principal<i style="margin-left: 5px; vertical-align: middle;" class="material-icons">home</i>
                                </a>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/users/list-users.blade.php
@extends('layouts.app')
@section('content')
        <div class="container" style="margin-top: 2px; text-align: center;">
          @if(session('msj'))
              <div class="alert alert-success alert-dismissible fade show" role="alert">
                      {{session('msj')}}
                  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                  </button>
              </div>
          @endif
          @if(count($errors)>0)
              @foreach($errors->all() as $error)
                  <div class="alert alert-danger alert-dismissible fade show" role="alert">
                          {{$error}}
                      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                      <span aria-hidden="true">&times;</span>
                      </button>
                  </div>
              @endforeach
          @endif
        </div>
        <div class="site-content">
            <div class="demo-wrapper">
                <div class="bd-content">
                        <h2 style="text-align: center; font-size: 30px;">Usuarios</h2>
                </div>
                <form class="tablas">
                <div class="table-container">
                <table class="table table-bordered table-striped" style="text-align: center" id="tabla">
                  <thead style="text-align: center" class="thead-dark">
                        <th style="text-align: center">Nombre Completo</th>
                        <th style="text-align: center">Email</th>
                        <th></th>
                    </tr>
                  </thead>
                    <tbody>
                      @foreach($users as $user)
                      <tr>
                        <td>{{$user->name}}</td>
                        <td>{{$user->email}}</td>
                        <td>
                          <a class="btn btn-primary btn-xs" id="botones" title="Editar Usuario" href="{{ route('users.edit', $user->id) }}"><i class="material-icons">edit</i></a>
                        </td>
                      </tr>
                     @endforeach
                  </tbody>
                </table>
                </form>
            </div>
          </div>
        </div>
        <script>
          $(document).ready(function(){
          $('#tabla').DataTable( {
              "lengthMenu": [[5, 10, 15], [5, 10, 15]],
              language: {
                    "emptyTable": "No hay donaciones de personas registradas actualmente!",
                    "info": "Mostrando de _START_ a _END_ de un total de _TOTAL_ registros",
                    "infoEmpty": "Mostrando 0 to 0 of 0 Registros",
                    "infoFiltered": "(Filtrado de un total de _MAX_ total registros)",
                    "lengthMenu": "Mostrar _MENU_ Registros",
                    "loadingRecords": "Cargando...",
                    "processing": "Procesando...",
                    "search": "Buscar:",
                    "zeroRecords": "Sin resultados encontrados",
                    "paginate": {
                    "first": "Primero",
                    "last": "Ultimo",
                    "next": "Siguiente",
                    "previous": "Anterior"
                  }
              },
            });
          });
        </script>
        <!-- /.site-footer -->
        <footer class="site-footer">
            <div class="mr-auto">
              Prueba PHP - Juan Moreno
            </div>
        </footer>
@endsection

resources/views/users/update-session-user.blade.php
@extends('layouts.app')
@section('content')
	<section class="container">
			<div style="margin-top: 18px;">
				<h3 style="text-align: center;">Modificar Mis Datos De Usuario</h3>
					<form method="post" style="margin-top: 20px; margin-bottom: 3%; padding-left: 36%;" action="{{ route('update-user', $users->id)}}" autocomplete="off">
						@csrf
						@method('PUT')
						<label for="name">Nombre Completo</label>
						<input name="name" type="text" value="{{$users->name}}" size="20" style="width: 300px;" class="form-control" onkeypress="return soloLetras(event)">
						<label for="email">Correo Electrónico</label>
						<input name="email" type="text" value="{{$users->email}}" size="20" style="width: 300px;" class="form-control">

						<a href="{{ route('home') }}" class="btn btn-danger" style="margin-top: 20px;">Cancelar</a>
						<input type="submit" value="Actualizar" style="margin-top: 20px;" class="btn btn-success">
					</form>
					<a href="{{ route('change-user-password') }}" class="btn btn-primary" id="botones" style="margin-left: 37%; width: 280px; border-radius: 28px;">Actualizar Mi Contraseña
					<i class="material-icons iconos">lock</i></a>
			</div>
	</section>
@endsection

resources/views/users/update-user.blade.php
@extends('layouts.app')
@section('content')
	<section class="container">
			<div style="margin-top: 8px;">
				<h2 style="text-align: center;">Modificar Usuario</h2>
					<form method="post" style="margin-top: 20px; margin-bottom: 3%; padding-left: 36%;" action="{{ route('users.update', $users->id)}}" autocomplete="off">
						@csrf
						@method('PUT')
						<label for="name">Nombre Completo</label>
						<input name="name" type="text" value="{{$users->name}}" size="20" style="width: 300px;" class="form-control" onkeypress="return soloLetras(event)">
						<label for="email">Correo Electrónico</label>
						<input name="email" type="email" value="{{$users->email}}" size="20" style="width: 300px;" class="form-control">

						<a href="{{ route('users') }}" class="btn btn-danger" style="margin-top: 20px;">Cancelar</a>
						<input type="submit" value="Actualizar" style="margin-top: 20px;" class="btn btn-success">
					</form>
			</div>
	</section>
@endsection