routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

Auth::routes();

/* Rutas del Administrador */
Route::group(['middleware' => 'admin'], function () {
    Route::resource('users', 'UserController');
    Route::get('users', 'UserController@index')->name('users');

    Route::get('listar_por_usuarios', 'ProcesosController@listar_por_usuarios')->name('listar_por_usuarios');
});

/* Rutas Generales */
Route::group(['middleware' => 'auth'], function () {
    /* Página principal */
    Route::get('/home', 'HomeController@index')->name('home');
    /* Rutas de procesos */
    Route::resource('procesos', 'ProcesosController');
    Route::get('procesos', 'ProcesosController@index')->name('procesos');
    /* Rutas de Perfil de usuario */
    Route::resource('user', 'UserController');
    Route::get('edit-user, {id}', 'UserController@editSessionUser')->name('edit-user');
    Route::put('update-user, {id}', 'UserController@updateSessionUser')->name('update-user');
    Route::get('change-user-password','UserController@changeUserPassword')->name('change-user-password');
    Route::post('saveNewPassword','UserController@saveNewPassword')->name('saveNewPassword');
});

app/Models/Proceso.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Proceso extends Model
{
    // modelo de la tabla procesos
    protected $table = "procesos";

    // foraneas
    public function Sede(){
      return $this->hasOne('App\Models\sede','id','sede_id');
    }

    public function User(){
      return $this->hasOne('App\User','id','user_id');
    }
}

app/Http/Controllers/ProcesosController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Auth;
use Jenssegers\Date\Date;
use App\Models\Proceso;
use App\Models\Sede;
use App\User;


class ProcesosController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        // consulta de procesos por id de usuario en sesión
        $procesos = Proceso::orderBy('id','ASC')
                            ->where('user_id', '=', $id = Auth::id())
                            ->get();
        return view('procesos.list-procesos', compact('procesos'));
    }

    public function listar_por_usuarios()
    {
        // consultar procesos de todos los usuarios
        $procesos = Proceso::orderBy('id','ASC')->get();
        return view('procesos.list-procesos-usuarios', compact('procesos'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        // consulta a la tabla sedes
        $sedes = Sede::all();
        // redirección a vista de crear proceso, pasando la informacion de sedes
        return \View::make('procesos.new-proceso', compact('sedes'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        // guardar los datos del proceso
        $proceso = new \App\Models\Proceso();
        // datos traidos de la vista
        $proceso->numero_proceso = $request->numero_proceso;
        $proceso->descripcion = $request->descripcion;
        $proceso->fecha_creacion = $request->fecha_creacion;
        $proceso->sede_id = $request->sede_id;
        $proceso->presupuesto = $request->presupuesto;
        $proceso->user_id = Auth::id();

        // validacion de campos (solo en caso de no funcionar las validaciones de la vista)
        $validatedData = $request->validate([
            'numero_proceso' => 'required|string|min:8|max:8',
            'descripcion' => 'required|string|max:200',
            'fecha_creacion' => 'required',
            'sede_id' => 'required',
            'presupuesto' => 'required|max:20'
        ]);

        // acción guardar y retorno de mensajes
        if($proceso->save()) {
          return redirect('/procesos')->with('msj','Proceso registrado correctamente.');
         }else{
          return redirect('/procesos')->with('msjerror','Ha sucedido un error al registrar el Proceso.');
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        // redirección a la vista editar proceso con la información de la tabla sedes
        $proceso = Proceso::find($id);
        $sedes = Sede::all();
        return \View::make('procesos.update-proceso', compact('proceso', 'sedes'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        // actualizar información del proceso
        $proceso = Proceso::find($id);

        $proceso->numero_proceso = $request->numero_proceso;
        $proceso->descripcion = $request->descripcion;
        $proceso->fecha_creacion = $request->fecha_creacion;
        $proceso->sede_id = $request->sede_id;
        $proceso->presupuesto = $request->presupuesto;
        $proceso->user_id = Auth::id();

        // validacion de campos (solo en caso de no funcionar las validaciones de la vista)
        $validatedData = $request->validate([
            'numero_proceso' => 'required|string|min:8|max:8',
            'descripcion' => 'required|string|max:200',
            'fecha_creacion' => 'required',
            'sede_id' => 'required',
            'presupuesto' => 'required|max:20'
        ]);

        // actualziación en base de datos y envio de mensajes
        if ($proceso->save()) {
          return redirect('/procesos')->with('msj','Información del Proceso actualizada correctamente.');
         }else{
          return redirect('/procesos')->with('msjerror','Ha sucedido un error al actualizar la Información del Proceso.');
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/procesos/list-procesos-usuarios.blade.php
@extends('layouts.app')
@section('content')
            <div class="container" style="margin-top: 2px; text-align: center;">
              @if(session('msj'))
                  <div class="alert alert-success alert-dismissible fade show" role="alert">
                          {{session('msj')}}
                      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                      <span aria-hidden="true">&times;</span>
                      </button>
                  </div>
              @endif
              @if(count($errors)>0)
                  @foreach($errors->all() as $error)
                      <div class="alert alert-danger alert-dismissible fade show" role="alert">
                              {{$error}}
                          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                          <span aria-hidden="true">&times;</span>
                          </button>
                      </div>
                  @endforeach
              @endif
            </div>
            <!-- /.site-header -->
            <div class="site-content">
            <div class="demo-wrapper">
                <!-- /.demo-header -->
                <div class="bd-content">
                        <h2 class="mb-4" style="text-align: center; font-size: 30px;">Procesos Por Usuario</h2>
                </div>
                <a href="{{ route('procesos.create') }}" id="botones" class="btn btn-primary btn-registrar">Registrar Proceso
                  <i class="material-icons iconos">add_to_photos</i></a>
                <div class="tablas">
                  <table class="table table-bordered table-striped" id="tabla" >
                  <thead class="thead-dark">
                        <th style="text-align: center;">Número de Proceso</th>
                        <th style="text-align: center;">Descripción</th>
                        <th style="text-align: center;">Fecha de Creación del Proceso</th>
                        <th style="text-align: center;">Sede</th>
                        <th style="text-align: center;">Presupuesto en Pesos Colombianos</th>
                        <th style="text-align: center;">Presupuesto en Dolares</th>
                        <th style="text-align: center;">Nombre Usuario</th>
                    </tr>
                  </thead>
                    <tbody>
                      @foreach($procesos as $proceso)
                      <tr>
                        <td>{{$proceso->numero_proceso}}</td>
                        <td>{{$proceso->descripcion}}</td>
                        <td>{{Date::parse($proceso->fecha_creacion)->format('d / F / Y')}}</td>
                        <td>{{$proceso->Sede->nombre}}</td>
                        <td>${{number_format($proceso->presupuesto, 0, '', '.')}}</td>
                        <td>USD {{number_format($proceso->presupuesto*0.00032, 0, '', '.')}}</td>
                        <td>{{$proceso->User->name}}</td>
                      </tr>
                     @endforeach
                  </tbody>
                </table>
                <script>
                  $(document).ready(function(){
                  $('#tabla').DataTable( {
                      "lengthMenu": [[5, 10, 15], [5, 10, 15]],
                      language: {
                            "emptyTable": "No hay procesos registrados actualmente!",
                            "info": "Mostrando de _START_ a _END_ de un total de _TOTAL_ registros",
                            "infoEmpty": "Mostrando 0 a 0 de 0 Registros",
                            "infoFiltered": "(Filtrado de un total de _MAX_ total registros)",
                            "lengthMenu": "Mostrar _MENU_ Registros",
                            "loadingRecords": "Cargando...",
                            "processing": "Procesando...",
                            "search": "Buscar:",
                            "zeroRecords": "Sin resultados encontrados",
                            "paginate": {
                            "first": "Primero",
                            "last": "Ultimo",
                            "next": "Siguiente",
                            "previous": "Anterior"
                          }
                      },
                    });
                  });
                </script>
                </div>
              </div>
              </div>

            <!-- /.site-footer -->
            <footer class="site-footer">
                <div class="mr-auto">
                  Prueba PHP - Juan Moreno
                </div>
            </footer>

@endsection

resources/views/procesos/list-procesos.blade.php
@extends('layouts.app')
@section('content')
            <div class="container" style="margin-top: 2px; text-align: center;">
              @if(session('msj'))
                  <div class="alert alert-success alert-dismissible fade show" role="alert">
                          {{session('msj')}}
                      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                      <span aria-hidden="true">&times;</span>
                      </button>
                  </div>
              @endif
              @if(count($errors)>0)
                  @foreach($errors->all() as $error)
                      <div class="alert alert-danger alert-dismissible fade show" role="alert">
                              {{$error}}
                          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                          <span aria-hidden="true">&times;</span>
                          </button>
                      </div>
                  @endforeach
              @endif
            </div>
            @if(Auth::user()->hasRole('user'))
            <!-- /.site-header -->
            <div class="site-content">
            <div class="demo-wrapper">
                <!-- /.demo-header -->
                <div class="bd-content">
                        <h2 class="mb-4" style="text-align: center; font-size: 30px;">Procesos Creados</h2>
                </div>
                <a href="{{ route('procesos.create') }}" id="botones" class="btn btn-primary btn-registrar">Registrar Proceso
                  <i class="material-icons iconos">add_to_photos</i></a>
                <div class="tablas">
                  <table class="table table-bordered table-striped" id="tabla" >
                  <thead class="thead-dark">
                    <tr style="vertical-align: middle">
                      <th style="text-align: center;">Número de Proceso</th>
                      <th style="text-align: center;">Descripción</th>
                      <th style="text-align: center;">Fecha de Creación del Proceso</th>
                      <th style="text-align: center;">Sede</th>
                      <th style="text-align: center;">Presupuesto en Pesos Colombianos</th>
                      <th style="text-align: center;">Presupuesto en Dolares</th>
                      <th></th>
                    </tr>
                  </thead>
                    <tbody>
                      @foreach($procesos as $proceso)
                      <tr>
                        <td>{{$proceso->numero_proceso}}</td>
                        <td>{{$proceso->descripcion}}</td>
                        <td>{{Date::parse($proceso->fecha_creacion)->format('d / F / Y')}}</td>
                        <td>{{$proceso->Sede->nombre}}</td>
                        <!-- formato para pesos colombianos -->
                        <td>${{number_format($proceso->presupuesto, 0, '', '.')}}</td>
                        <!-- conversión a dolares (equivalencia: 1 (COP) = 0.00032 (USD)) -->
                        <td>USD {{number_format($proceso->presupuesto*0.00032, 0, '', '.')}}</td>
                        <td>
                          <a class="btn btn-primary btn-xs" title="Editar Proceso" id="botones" href="{{ route('procesos.edit', $proceso->id) }}"><i class="material-icons">edit</i></a>
                        </td>
                      </tr>
                     @endforeach
                  </tbody>
                </table>
                <script>
                  $(document).ready(function(){
                  $('#tabla').DataTable( {
                      "lengthMenu": [[5, 10, 15], [5, 10, 15]],
                      language: {
                            "emptyTable": "No hay procesos registrados actualmente.",
                            "info": "Mostrando de _START_ a _END_ de un total de _TOTAL_ registros",
                            "infoEmpty": "Mostrando 0 a 0 de 0 Registros",
                            "infoFiltered": "(Filtrado de un total de _MAX_ total registros)",
                            "lengthMenu": "Mostrar _MENU_ Registros",
                            "loadingRecords": "Cargando...",
                            "processing": "Procesando...",
                            "search": "Buscar:",
                            "zeroRecords": "Sin resultados encontrados",
                            "paginate": {
                            "first": "Primero",
                            "last": "Ultimo",
                            "next": "Siguiente",
                            "previous": "Anterior"
                          }
                      },
                    });
                  });
                </script>
                </div>
              </div>
              </div>
              @else
              <p style="text-align: center;">Solo el usuario que no es "Administrador" puede crear o editar un proceso.</p>
              @endif

            <!-- /.site-footer -->
            <footer class="site-footer">
                <div class="mr-auto">
                  Prueba PHP - Juan Moreno
                </div>
            </footer>

@endsection

resources/views/procesos/new-proceso.blade.php
@extends('layouts.app')
@section('content')
	<section class="container">
			@if(session('msjerror'))
					<div class="alert alert-warning alert-dismissible fade show" role="alert" style="text-align: center;">
									{{session('msjerror')}}
							<button type="button" class="close" data-dismiss="alert" aria-label="Close">
							<span aria-hidden="true">&times;</span>
							</button>
					</div>
			@endif
			<div style="margin-top: 5px;">
				<h2 style="text-align: center;">Registrar Proceso</h2>
					<form style="margin-top: 8px; margin-bottom: 3%; padding-left: 36%;" method="post" action="{{route('procesos.store')}}" autocomplete="off">
						{{csrf_field()}}

						<label for="numero_proceso">Número del Proceso</label>
						<input name="numero_proceso" type="text" style="width: 300px;" class="form-control" placeholder="el número debe tener 8 caracteres exactos" maxlength="8" minlength="8" required>
						<label for="descripcion">Descripción</label>
						<textarea name="descripcion" maxlength="200" style="width: 300px;" class="form-control" placeholder="ingrese máximo 200 caracteres" required></textarea>
						<label for="fecha" class="control-label">Fecha de Creación</label>
							<div class="input-group date"><span class="input-group-addon"><i class="material-icons dp48">insert_invitation</i></span>
								<input type="text" name="fecha_creacion" value="{{Date::now()->format('Y-m-d')}}" class="input_icono" readonly required/>
							</div>
						<label for="sede_id">Sede</label>
						<div class="input-group"><span class="input-group-addon"><i class="material-icons dp48">location_on</i></span>
						<select class="input_icono" name="sede_id" required>
									<option value="">seleccione...</option>
									@foreach($sedes as $sede)
									<option value="{{$sede->id}}">{{$sede->nombre}}</option>
									@endforeach
				     </select>
						 </div>
						<label for="presupuesto">Presupuesto COP (En pesos colombianos)</label>
						<div class="input-group"><span class="input-group-addon"><i class="material-icons dp48">attach_money</i></span>
							<input name="presupuesto" type="number" class="input_icono" onkeypress="return validaNum(event)"
							title="por favor ingrese la suma sin puntos, comas, espacios, ni caracteres especiales" maxlength="20" required />
						</div>

					  <a  href="{{ route('procesos') }}" class="btn btn-danger" style="margin-top: 20px; margin-left: 8%;">Cancelar</a>
						<input type="submit" value="Registrar" style="margin-top: 20px;" class="btn btn-success">
					</form>
			</div>
	</section>

@endsection

resources/views/procesos/update-proceso.blade.php
@extends('layouts.app')
@section('content')
	<section class="container">
			<div style="margin-top: 18px;">
				<h2 style="text-align: center;">Actualizar Información del Proceso</h2>
					<form method="post" style="margin-top: 20px; margin-bottom: 3%; padding-left: 36%;" action="{{ route('procesos.update', $proceso->id)}}" autocomplete="off">
						@csrf
						@method('PUT')
						<label for="numero_proceso">Número del Proceso</label>
						<input name="numero_proceso" type="text" style="width: 300px;" class="form-control" value="{{$proceso->numero_proceso}}" placeholder="el número debe tener 8 caracteres exactos" maxlength="8" minlength="8" required>
						<label for="descripcion">Descripción</label>
						<textarea name="descripcion" maxlength="200" style="width: 300px;" class="form-control" placeholder="ingrese máximo 200 caracteres" required>{{$proceso->descripcion}}</textarea>
						<label for="fecha" class="control-label">Fecha de Creación</label>
							<div class="input-group date"><span class="input-group-addon"><i class="material-icons dp48">insert_invitation</i></span>
								<input type="text" name="fecha_creacion" value="{{$proceso->fecha_creacion}}" class="input_icono" id="datepicker" required/>
							</div>
						<label for="sede_id">Sede</label>
						<div class="input-group"><span class="input-group-addon"><i class="material-icons dp48">location_on</i></span>
							<select class="input_icono" name="sede_id">
										@foreach($sedes as $sede)
										<option value="{{$sede->id}}" {{$proceso->sede_id==$sede->id? 'selected': null }}>{{$sede->nombre}}</option>
										@endforeach
							</select>
						 </div>
						<label for="presupuesto">Presupuesto COP (En pesos colombianos)</label>
						<div class="input-group"><span class="input-group-addon"><i class="material-icons dp48">attach_money</i></span>
							<input name="presupuesto" type="text" value="{{$proceso->presupuesto}}" class="input_icono" onkeypress="return validaNum(event)"
							title="por favor ingrese la suma sin puntos, comas, espacios, ni caracteres especiales" maxlength="20" required />
						</div>

						<a href="{{ route('procesos') }}" class="btn btn-danger" style="margin-top: 20px;">Cancelar</a>
						<input type="submit" value="Actualizar" style="margin-top: 20px;" class="btn btn-success">
					</form>
			</div>
	</section>
@endsection